baseURL = "http://hayleyevans.net/"
enableEmoji = true
languageCode = "en-us"
theme = "paperback"
title = "Hayley Evans"
[[menu.main]]
name = "Writing"
url = "/#writing"
weight = 1
[[menu.main]]
name = "Editing"
url = "/#editing"
weight = 2
[[menu.main]]
name = "Interviews"
url = "/#interviews"
weight = 3
[[menu.main]]
name = "About"
url = "/about"
weight = 5
[params]
image = "/uploads/cover-image-1.jpg"
instagram = "https://www.instagram.com/voidxwitch/"
linkedin = "https://www.linkedin.com/in/hayleyev/"
sitedescription = "Portfolio for writer/editor Hayley Evans"
twitter = "https://twitter.com/voidxwitch"
