---
label: project
hide_body: false
fields:
- type: file
  name: picture
  label: Picture
- type: textarea
  name: quote
  label: Quote
  config:
    required: true
- type: text
  label: projectUrl
  name: projecturl
  config:
    required: false
- type: text
  name: title
  label: Title
  config:
    required: true
- type: text
  name: type
  label: Type
  config:
    required: true
  default: writing
- type: text
  name: author
  label: Author
- type: text
  name: authorurl
  label: authorurl
  description: link to author website
- type: number
  name: weight
  label: weight
  description: Ordering of projects on home page, lower number, higher on the page
pages:
- content/projects/interview-with-evelyn-bencicova.md
- content/projects/art-by-stephanie-inagaki.md
- content/projects/interview-with-gottfried-helnwein.md
- content/projects/dark-art-by-dehn-sora.md
- content/projects/suburban-occult-joseph-haxan.md
- content/projects/the-nature-of-fear-nicola-samori.md
- content/projects/colby-v-edwards-post-apocalyptic-existence.md
- content/projects/designs-by-fangophilia.md
- content/projects/photography-by-laura-makabresku-1.md
- content/projects/soledades.md
- content/projects/sculptures-by-berlinde-de-bruyckere.md
- content/projects/photography-by-helena-darling.md
- content/projects/light-through-shadow-krist-mort.md
- content/projects/dark-paranormal-femininity-nynewe.md
- content/projects/interview-with-placide-avantia.md
- content/projects/shadow-sculptures-by-tim-noble-sue-webster.md
- content/projects/nathan-coley-s-illuminated-text-sculptures.md
- content/projects/julian-feeld-la-forêt.md
- content/projects/mrs-langlois-house.md
- content/projects/the-modernist-world.md
- content/projects/10-rogue-taxidermy-artists.md
- content/projects/disfigured-flesh-sarah-sitkin.md
- content/projects/concrete-sex-sasha-kurmaz.md
- content/projects/survival.md
- content/projects/test.md
- content/projects/in-sickness-and-beauty-evelyn-bencicova.md
