---
label: project
hide_body: true
is_partial: false
fields:
- type: file
  name: picture
  label: Picture
- type: textarea
  name: quote
  label: Quote
  config:
    required: true
- type: text
  label: projectUrl
  name: projecturl
  config:
    required: true
- type: text
  name: title
  label: Title
  config:
    required: true
- type: text
  name: type
  label: Type
  config:
    required: true
  default: writing
- type: text
  name: author
  label: Author
pages:
- content/projects/test.md
- content/projects/in-sickness-and-beauty-evelyn-bencicova.md
