---
label: project
hide_body: true
is_partial: false
fields:
- type: file
  name: picture
  label: Picture
- type: textarea
  name: quote
  label: Quote
  config:
    required: true
- type: text
  label: projectUrl
  name: projecturl
  config:
    required: true
- type: text
  name: title
  label: Title
  config:
    required: true
- type: text
  name: type
  label: Type
  config:
    required: true
  default: writing
- type: text
  name: author
  label: Author
pages:
- content/projects/test.md
- content/projects/in-sickness-and-beauty-evelyn-bencicova.md
- content/projects/concrete-sex-sasha-kurmaz.md
- content/projects/disfigured-flesh-sarah-sitkin.md
- content/projects/suburban-occult-joseph-haxan.md
- content/projects/bionic-bodies-chromat.md
- content/projects/colby-v-edwards-post-apocalyptic-existence.md
- content/projects/julian-feeld-la-forêt.md
- content/projects/nathan-coley-s-illuminated-text-sculptures.md
- content/projects/herbert-baglione-s-eerie-shadows.md
- content/projects/the-nature-of-fear-nicola-samori.md
- content/projects/shadow-sculptures-by-tim-noble-sue-webster.md
- content/projects/interview-with-placide-avantia.md
- content/projects/dark-paranormal-femininity-nynewe.md
- content/projects/light-through-shadow-krist-mort.md
- content/projects/interview-with-gottfried-helnwein.md
- content/projects/photography-by-helena-darling.md
- content/projects/interview-with-antony-micallef.md
